- name: install latest libvirtd 
  apt:
    name: libvirt-bin
    update_cache: yes
    state: latest

- name: run libvirt daemon
  service:
    name: libvirt-bin
    state: running
    enabled: true
        
- name: install latest qemu-kvm
  apt:
    name: qemu-kvm
    update_cache: yes
    state: latest

- name: install latest qemu-kvm-spice
  apt:
    name: qemu-kvm-spice
    update_cache: yes
    state: latest

- name: install libvirt python library
  apt: name=python-libvirt state=present

- name: update vagrant user
  user: name=vagrant groups=libvirtd append=yes
  
- name: define vm
  virt: name=alpha
        command=define
        xml="{{ lookup('template', 'kvm-template.xml.j2') }}"
        
- name: start vm
  virt: name=alpha state=running
