- name: ensure apache2 latest version
  apt:
    name: apache2
    update_cache: yes
    state: latest
  
- name: enable mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
    
- name: check old index
  stat: path=/var/www/html/index.old 
  register: old_index

- name: check standard index
  stat: path=/var/www/html/index.html 
  register: standard_index

- name: conditional move  
  command: mv /var/www/html/index.html /var/www/html/index.old
  when: (old_index.stat.exists == False)
    and (standard_index.stat.exists == True)

- name: template hello world index
  template: src=hello_world_index.html.j2 dest=/var/www/html/index.html
  